apiVersion: v1
kind: Service
metadata:
  name: aiclient-service
spec:
  type: ClusterIP
  ports:
    - name: default-port
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ai         # Selects pods with this label
