apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiclient-deployment
  labels:
    app: ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: aiclient-configmap
      containers:
        - name: aiclient
          image: tethmado/ai-client:0.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /src/main/resources
