apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-fetcher-deployment
  namespace: stk-dbmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stock-fetcher
  template:
    metadata:
      labels:
        app: stock-fetcher
    spec:
      containers:
      - name: stock-fetcher
        image: tethmado/db:0.0.1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: stock-app-config

