apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: tethmado/db:0.0.1
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: db-config

