---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: stk-dbmicroservice
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: main-app
      protocol: TCP
      port: 5000
      targetPort: db
