
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - name: default-port
      protocol: TCP
      port: 5010
      targetPort: frontend-cont

