
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: stk-poster
spec:
  selector:
    app: frontend
  ports:
    - name: default-port
      protocol: TCP
      port: 5010
      targetPort: frontend-container

